### ISSUE TITLE
Any sort of todo list for this library?

### ISSUE THREAD

**Issue by lukemcdo** [zanaptak/PcgRandom#2]
Hi, I consume this library in a few of my projects and while right now it does quite enough for my uses, I'd like to know if there's any work that needs done with the library.

**Comment by zanaptak** [comment]
No, not really. I think I covered most of the base algorithms or at least everything I thought was useful. I know there is additional more advanced stuff from the PCG paper but I'm not really looking into anything like that.

The only small thing I've been thinking of is that I might make Pcg.NextDouble generate from the max 53 bits instead of 32 bits for better quality. I've also started doing some cleanup on my libraries and will probably bump this to 1.0 in the coming weeks anyway despite no major changes.

**Comment by lukemcdo** [comment]
This makes sense to me, I was surprised by the low version number for something that seemed complete. I’m just using the library for randomness in a few small card/board games though.

Thank you for your work and congrats on a 1.0-worthy library!

**Comment by lukemcdo** [comment]
Hmm ok feel free to tell me if this is a bad idea, but would you be interested in exposing a GetSeed function of some sort? Or should I just choose seeds some other way? (Such as using a default-seeded instance to generate my seed, then seed using that.)
